<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v13/enums/extension_type.proto

namespace Google\Ads\GoogleAds\V13\Enums\ExtensionTypeEnum;

use UnexpectedValueException;

/**
 * Possible data types for an extension in an extension setting.
 *
 * Protobuf type <code>google.ads.googleads.v13.enums.ExtensionTypeEnum.ExtensionType</code>
 */
class ExtensionType
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    public const UNSPECIFIED = 0;
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    public const UNKNOWN = 1;
    /**
     * None.
     *
     * Generated from protobuf enum <code>NONE = 2;</code>
     */
    public const NONE = 2;
    /**
     * App.
     *
     * Generated from protobuf enum <code>APP = 3;</code>
     */
    public const APP = 3;
    /**
     * Call.
     *
     * Generated from protobuf enum <code>CALL = 4;</code>
     */
    public const CALL = 4;
    /**
     * Callout.
     *
     * Generated from protobuf enum <code>CALLOUT = 5;</code>
     */
    public const CALLOUT = 5;
    /**
     * Message.
     *
     * Generated from protobuf enum <code>MESSAGE = 6;</code>
     */
    public const MESSAGE = 6;
    /**
     * Price.
     *
     * Generated from protobuf enum <code>PRICE = 7;</code>
     */
    public const PRICE = 7;
    /**
     * Promotion.
     *
     * Generated from protobuf enum <code>PROMOTION = 8;</code>
     */
    public const PROMOTION = 8;
    /**
     * Sitelink.
     *
     * Generated from protobuf enum <code>SITELINK = 10;</code>
     */
    public const SITELINK = 10;
    /**
     * Structured snippet.
     *
     * Generated from protobuf enum <code>STRUCTURED_SNIPPET = 11;</code>
     */
    public const STRUCTURED_SNIPPET = 11;
    /**
     * Location.
     *
     * Generated from protobuf enum <code>LOCATION = 12;</code>
     */
    public const LOCATION = 12;
    /**
     * Affiliate location.
     *
     * Generated from protobuf enum <code>AFFILIATE_LOCATION = 13;</code>
     */
    public const AFFILIATE_LOCATION = 13;
    /**
     * Hotel callout
     *
     * Generated from protobuf enum <code>HOTEL_CALLOUT = 15;</code>
     */
    public const HOTEL_CALLOUT = 15;
    /**
     * Image.
     *
     * Generated from protobuf enum <code>IMAGE = 16;</code>
     */
    public const IMAGE = 16;

    private static array $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::NONE => 'NONE',
        self::APP => 'APP',
        self::CALL => 'CALL',
        self::CALLOUT => 'CALLOUT',
        self::MESSAGE => 'MESSAGE',
        self::PRICE => 'PRICE',
        self::PROMOTION => 'PROMOTION',
        self::SITELINK => 'SITELINK',
        self::STRUCTURED_SNIPPET => 'STRUCTURED_SNIPPET',
        self::LOCATION => 'LOCATION',
        self::AFFILIATE_LOCATION => 'AFFILIATE_LOCATION',
        self::HOTEL_CALLOUT => 'HOTEL_CALLOUT',
        self::IMAGE => 'IMAGE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExtensionType::class, \Google\Ads\GoogleAds\V13\Enums\ExtensionTypeEnum_ExtensionType::class);

