<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v13/enums/minute_of_hour.proto

namespace Google\Ads\GoogleAds\V13\Enums\MinuteOfHourEnum;

use UnexpectedValueException;

/**
 * Enumerates of quarter-hours. For example, "FIFTEEN"
 *
 * Protobuf type <code>google.ads.googleads.v13.enums.MinuteOfHourEnum.MinuteOfHour</code>
 */
class MinuteOfHour
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    public const UNSPECIFIED = 0;
    /**
     * The value is unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    public const UNKNOWN = 1;
    /**
     * Zero minutes past the hour.
     *
     * Generated from protobuf enum <code>ZERO = 2;</code>
     */
    public const ZERO = 2;
    /**
     * Fifteen minutes past the hour.
     *
     * Generated from protobuf enum <code>FIFTEEN = 3;</code>
     */
    public const FIFTEEN = 3;
    /**
     * Thirty minutes past the hour.
     *
     * Generated from protobuf enum <code>THIRTY = 4;</code>
     */
    public const THIRTY = 4;
    /**
     * Forty-five minutes past the hour.
     *
     * Generated from protobuf enum <code>FORTY_FIVE = 5;</code>
     */
    public const FORTY_FIVE = 5;

    private static array $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::ZERO => 'ZERO',
        self::FIFTEEN => 'FIFTEEN',
        self::THIRTY => 'THIRTY',
        self::FORTY_FIVE => 'FORTY_FIVE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MinuteOfHour::class, \Google\Ads\GoogleAds\V13\Enums\MinuteOfHourEnum_MinuteOfHour::class);

