<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v13/enums/search_term_match_type.proto

namespace Google\Ads\GoogleAds\V13\Enums\SearchTermMatchTypeEnum;

use UnexpectedValueException;

/**
 * Possible match types for a keyword triggering an ad, including variants.
 *
 * Protobuf type <code>google.ads.googleads.v13.enums.SearchTermMatchTypeEnum.SearchTermMatchType</code>
 */
class SearchTermMatchType
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    public const UNSPECIFIED = 0;
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    public const UNKNOWN = 1;
    /**
     * Broad match.
     *
     * Generated from protobuf enum <code>BROAD = 2;</code>
     */
    public const BROAD = 2;
    /**
     * Exact match.
     *
     * Generated from protobuf enum <code>EXACT = 3;</code>
     */
    public const EXACT = 3;
    /**
     * Phrase match.
     *
     * Generated from protobuf enum <code>PHRASE = 4;</code>
     */
    public const PHRASE = 4;
    /**
     * Exact match (close variant).
     *
     * Generated from protobuf enum <code>NEAR_EXACT = 5;</code>
     */
    public const NEAR_EXACT = 5;
    /**
     * Phrase match (close variant).
     *
     * Generated from protobuf enum <code>NEAR_PHRASE = 6;</code>
     */
    public const NEAR_PHRASE = 6;

    private static array $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::BROAD => 'BROAD',
        self::EXACT => 'EXACT',
        self::PHRASE => 'PHRASE',
        self::NEAR_EXACT => 'NEAR_EXACT',
        self::NEAR_PHRASE => 'NEAR_PHRASE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SearchTermMatchType::class, \Google\Ads\GoogleAds\V13\Enums\SearchTermMatchTypeEnum_SearchTermMatchType::class);

