<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/errors/quota_error.proto

namespace Google\Ads\GoogleAds\V12\Errors\QuotaErrorEnum;

use UnexpectedValueException;

/**
 * Enum describing possible quota errors.
 *
 * Protobuf type <code>google.ads.googleads.v12.errors.QuotaErrorEnum.QuotaError</code>
 */
class QuotaError
{
    /**
     * Enum unspecified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    public const UNSPECIFIED = 0;
    /**
     * The received error code is not known in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    public const UNKNOWN = 1;
    /**
     * Too many requests.
     *
     * Generated from protobuf enum <code>RESOURCE_EXHAUSTED = 2;</code>
     */
    public const RESOURCE_EXHAUSTED = 2;
    /**
     * Access is prohibited.
     *
     * Generated from protobuf enum <code>ACCESS_PROHIBITED = 3;</code>
     */
    public const ACCESS_PROHIBITED = 3;
    /**
     * Too many requests in a short amount of time.
     *
     * Generated from protobuf enum <code>RESOURCE_TEMPORARILY_EXHAUSTED = 4;</code>
     */
    public const RESOURCE_TEMPORARILY_EXHAUSTED = 4;

    private static array $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::RESOURCE_EXHAUSTED => 'RESOURCE_EXHAUSTED',
        self::ACCESS_PROHIBITED => 'ACCESS_PROHIBITED',
        self::RESOURCE_TEMPORARILY_EXHAUSTED => 'RESOURCE_TEMPORARILY_EXHAUSTED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(QuotaError::class, \Google\Ads\GoogleAds\V12\Errors\QuotaErrorEnum_QuotaError::class);

