<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v14/enums/async_action_status.proto

namespace Google\Ads\GoogleAds\V14\Enums\AsyncActionStatusEnum;

use UnexpectedValueException;

/**
 * The async action status of the experiment.
 *
 * Protobuf type <code>google.ads.googleads.v14.enums.AsyncActionStatusEnum.AsyncActionStatus</code>
 */
class AsyncActionStatus
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    public const UNSPECIFIED = 0;
    /**
     * The value is unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    public const UNKNOWN = 1;
    /**
     * Action has not started.
     *
     * Generated from protobuf enum <code>NOT_STARTED = 2;</code>
     */
    public const NOT_STARTED = 2;
    /**
     * Action is in progress.
     *
     * Generated from protobuf enum <code>IN_PROGRESS = 3;</code>
     */
    public const IN_PROGRESS = 3;
    /**
     * Action has completed successfully.
     *
     * Generated from protobuf enum <code>COMPLETED = 4;</code>
     */
    public const COMPLETED = 4;
    /**
     * Action has failed.
     *
     * Generated from protobuf enum <code>FAILED = 5;</code>
     */
    public const FAILED = 5;
    /**
     * Action has completed successfully with warnings.
     *
     * Generated from protobuf enum <code>COMPLETED_WITH_WARNING = 6;</code>
     */
    public const COMPLETED_WITH_WARNING = 6;

    private static array $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::NOT_STARTED => 'NOT_STARTED',
        self::IN_PROGRESS => 'IN_PROGRESS',
        self::COMPLETED => 'COMPLETED',
        self::FAILED => 'FAILED',
        self::COMPLETED_WITH_WARNING => 'COMPLETED_WITH_WARNING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AsyncActionStatus::class, \Google\Ads\GoogleAds\V14\Enums\AsyncActionStatusEnum_AsyncActionStatus::class);

