<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/enums/preferred_content_type.proto

namespace Google\Ads\GoogleAds\V12\Enums\PreferredContentTypeEnum;

use UnexpectedValueException;

/**
 * Enumerates preferred content criterion type.
 *
 * Protobuf type <code>google.ads.googleads.v12.enums.PreferredContentTypeEnum.PreferredContentType</code>
 */
class PreferredContentType
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    public const UNSPECIFIED = 0;
    /**
     * The value is unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    public const UNKNOWN = 1;
    /**
     * Represents top content on YouTube.
     *
     * Generated from protobuf enum <code>YOUTUBE_TOP_CONTENT = 400;</code>
     */
    public const YOUTUBE_TOP_CONTENT = 400;

    private static array $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::YOUTUBE_TOP_CONTENT => 'YOUTUBE_TOP_CONTENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PreferredContentType::class, \Google\Ads\GoogleAds\V12\Enums\PreferredContentTypeEnum_PreferredContentType::class);

