<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/enums/user_list_date_rule_item_operator.proto

namespace Google\Ads\GoogleAds\V12\Enums\UserListDateRuleItemOperatorEnum;

use UnexpectedValueException;

/**
 * Enum describing possible user list date rule item operators.
 *
 * Protobuf type <code>google.ads.googleads.v12.enums.UserListDateRuleItemOperatorEnum.UserListDateRuleItemOperator</code>
 */
class UserListDateRuleItemOperator
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    public const UNSPECIFIED = 0;
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    public const UNKNOWN = 1;
    /**
     * Equals.
     *
     * Generated from protobuf enum <code>EQUALS = 2;</code>
     */
    public const EQUALS = 2;
    /**
     * Not Equals.
     *
     * Generated from protobuf enum <code>NOT_EQUALS = 3;</code>
     */
    public const NOT_EQUALS = 3;
    /**
     * Before.
     *
     * Generated from protobuf enum <code>BEFORE = 4;</code>
     */
    public const BEFORE = 4;
    /**
     * After.
     *
     * Generated from protobuf enum <code>AFTER = 5;</code>
     */
    public const AFTER = 5;

    private static array $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::EQUALS => 'EQUALS',
        self::NOT_EQUALS => 'NOT_EQUALS',
        self::BEFORE => 'BEFORE',
        self::AFTER => 'AFTER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserListDateRuleItemOperator::class, \Google\Ads\GoogleAds\V12\Enums\UserListDateRuleItemOperatorEnum_UserListDateRuleItemOperator::class);

