<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/enums/user_list_combined_rule_operator.proto

namespace Google\Ads\GoogleAds\V12\Enums\UserListCombinedRuleOperatorEnum;

use UnexpectedValueException;

/**
 * Enum describing possible user list combined rule operators.
 *
 * Protobuf type <code>google.ads.googleads.v12.enums.UserListCombinedRuleOperatorEnum.UserListCombinedRuleOperator</code>
 */
class UserListCombinedRuleOperator
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    public const UNSPECIFIED = 0;
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    public const UNKNOWN = 1;
    /**
     * A AND B.
     *
     * Generated from protobuf enum <code>AND = 2;</code>
     */
    public const PBAND = 2;
    /**
     * A AND NOT B.
     *
     * Generated from protobuf enum <code>AND_NOT = 3;</code>
     */
    public const AND_NOT = 3;

    private static array $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::PBAND => 'AND',
        self::AND_NOT => 'AND_NOT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  self::class. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', self::class, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserListCombinedRuleOperator::class, \Google\Ads\GoogleAds\V12\Enums\UserListCombinedRuleOperatorEnum_UserListCombinedRuleOperator::class);

